### ISSUE TITLE
"Keyboard routines" support is mostly absent

### ISSUE THREAD

**Issue by iamgreaser** [resttime/cl-liballegro#11]
First of all, thank you so much for making this work in such a way that I can actually do things with it.

For reference:

* OS: Void Linux amd64
* Lisp: SBCL 1.4.1
* Allegro: 5.2.2
* cl-liballegro: Git snapshot 237cc4800e10da3c06f6bc560aada293a0aac22a

I've managed to get the keyboard working, but it looks a bit like this:

```
(cffi:defcstruct keyboard-state
   (display :pointer)
   (__key_down__internal__ :int :count 8)) ; ceil 227/32

;; ... a lot of code omitted ...

(cffi:with-foreign-object (keyboard-state '(:struct keyboard-state))
  (al:get-keyboard-state keyboard-state)
  (do () ((al:key-down keyboard-state
                       (cffi:foreign-enum-value 'al::keycodes :escape)))
    (tick-game)
    (sleep 0.1)
    (al:get-keyboard-state keyboard-state)))
```

Here's where it gets really ugly:

* `keyboard-state` is declared completely opaque in cl-liballegro, while it's "conventionally opaque" in C. Allegro 5 requires that this state must be allocated by the program - it does not provide a method to create a new keyboard state object.
  * I have confirmed that I get corruption warning spam if I attempt to use `al::keyboard-state` followed by SBCL dropping into LDB.
* Keycodes are not exposed, so they need to be accessed using an unexported symbol.

Ideally it would be good to not need to use `cffi:with-foreign-object` or `cffi:foreign-enum`, but I'll leave it up to you as to whether that should be worked around or not.

With that said, I'm guessing I should probably be using the event system as per SDL, rather than the keyboard state snapshot system as per Allegro 4.

**Comment by resttime** [comment]
I was pretty busy so I just read issue not too long ago. I'm glad to fix stuff and keep shooting away with any questions/issues you might have. I'm quite happy anyone else is finding use for my bindings aside from me.

Yes, I would recommend using the event system as it's considered the modern way that's more efficient than just polling and I mean that without the bindings too. If you're interested in an example, you can check out (or use) the lispy interface that provides a game loop with a fixed-timestep for logic. The remaining time is given to rendering so interpolation can be done if passing something like a delta time to a rendering function. Otherwise there should be examples out in the web about how to use the allegro event system and combining with some game loop tutorial should give what's needed.

Either way you don't really have to worry since I'll still work on implementing more support for the keyboard or an easier way to work with it since it might be good for smaller things. When I have the time I'll try to have it done in a few days or before the weekend ends.

**Comment by resttime** [comment]
5611ddba539d9a4cc2bcbc1eb72f48d8cc29028d

I've written some macros to help poll the keyboard and mouse. The keyboard functions now accept any keywords defined by KEYCODES in constants.lisp as well.

Example has been added
```common-lisp
;;; Example demonstrating how to use the state macros for convinience
;; with-current-keyboard-state
;; with-current-mouse-state
(ql:quickload :cl-liballegro)

(defvar display)

(defun main ()
  ;; Create the display and load the input drivers
  (al:init)
  (al:install-keyboard)
  (al:install-mouse)
  (setf display (al:create-display 800 600))
  ;; This macro will initialize STATE by calling
  ;; (al:get-keyboard-state STATE) for you.  Use WITH-KEYBOARD-STATE
  ;; to leave uninitialized.
  (al:with-current-keyboard-state state
    (do () ((al:key-down state :escape)) ;; ESC terminates the loop
      (sleep 0.1)
      ;; Mouse state works like the keyboard state macros
      (al:with-current-mouse-state state
        ;; The mouse state can be exploded into a plist
        (let ((plist (cffi:mem-ref state '(:struct al:mouse-state))))
          (format t "X:~a Y:~a~%" (getf plist 'al:x) (getf plist 'al:y))))
      (al:get-keyboard-state state)))
  ;; All done let's cleanup
  (al:destroy-display display)
  (al:uninstall-system))
```
