### ISSUE TITLE
Optimizing Type Translators

### ISSUE THREAD

**Issue by resttime** [resttime/cl-liballegro#20]
Optimization by removing generic function calls: https://common-lisp.net/project/cffi/manual/html_node/Optimizing-Type-Translators.html#Optimizing-Type-Translators

**Comment by resttime** [comment]
Not needed, at least for now. See related issue #21

**Comment by lockie** [comment]
I've dived into this issue a little bit deeper this week, and it seems like there is big underlying problem. To quote [SBCL manual](https://sbcl.org/manual/#The-alien_002dfuncall-Primitive-1),
> Passing of structures by value is not implemented

...which means that a lot of liballegro functions would suffer from that and wouldn't be as performant under SBCL as they could be, since a lot of them take `ALLEGRO_COLOR` struct by-value, and CFFI has to perform a lot of runtime memory magic to shove that structure onto the stack.
This problem is not specific to liballegro, raylib and SFML seem to prefer passing color struct "by value" as well, and only SDL2, which originates from 1999, does not do that in its API, just a bunch of plain `int`s or `floats` as the color channel arguments :smile:
Here's a [tiny gist](https://gist.github.com/lockie/92de2610f22aca15448ab7acbaa6d4de) with calls to `disassemble` to illustrate the issue.
To conclude, I haven't tried the aforementioned type translators, but I bet they can't do much since SBCL does not support passing the structs through stack natively. I guess one could add struct-by-value support in SBCL, but that's over my depth :sweat_smile:

**Comment by resttime** [comment]
@lockie 
Bit of late reply but yeah that is the case. The optimization of type translators was referring to how CLOS uses a multiple dispatch system, i.e., type checking args to invoke the right method. Been a while, but IIRC the possible optimization targeting this would bring it closer to a static dispatch from a dynamic one through the use of macros.

There's actually some related history to this. Long ago the possibility of not passing structures by value was investigated. Not sure how correct/conformant this is but I found some interesting behaviour that might be undefined. 

So passing a foreign structure to a function by value essentially means pushing it onto the stack for the function call. Unless the struct, `ALLEGRO_COLOR`, has its size padded for memory alignment, that means when the struct pushed onto the stack the memory layout will have four floats and then call the function. In that case, wouldn't that be equivalent to the memory layout of a function which takes four individual floats pushed onto the stack?

![image](https://github.com/resttime/cl-liballegro/assets/2598904/7eebd3f5-3134-436c-9194-2fc69a8c5c1c)

With that assumption in mind a very early version of this library didn't use the `ALLEGRO_STRUCT` parameter for color routines. It defined them with 4 floats as arguments instead and it worked to my surprise.
https://github.com/resttime/cl-liballegro/blob/74ba63d9871ff6e86eb3a96198c9b45a6fe052a3/cl-liballegro.lisp#L612-L613 

Unfortunately it broke on different machine architecture e.g., x86 vs x64. Some kind of different type size, memory alignment, or other memory voodoo was happening. That was when I decided to use libffi. Related Issues #4 and #6.

The possibility of implementing this still exists with macros if the behaviour could work reliably on different architectures.

**Comment by lockie** [comment]
Oh I see, thanks for the input. That's interesting that the library worked like that previously.
I bet the fact that it broke on either x86 or x64 is due to that 32-bit long float was aligned to 64-bit word boundary on x64 or something like that.

Anyway, recently I've found out that using `SDL2_ttf` library also involves passing color struct by value, so in fact there wouldn't be much performance difference between full-fledged SDL2-based app and liballegro-based app (at least not significant one).
