### ISSUE TITLE
pls add LICENSE

### ISSUE THREAD

**Issue by ukH9YFxczKfxEnNECPyq** [resttime/cl-liballegro#24]
hi, your package used in some packages i use for some other packages 0_0
could you please add license in your project?

**Comment by resttime** [comment]
I follow the Allegro 5 license since this library is bindings to it. You can find it in the system definition of `cl-liballegro.asd`: https://github.com/resttime/cl-liballegro/blob/master/cl-liballegro.asd#L4

`:license "Allegro 5 - https://liballeg.org/license.html"`

As far as I can tell it's very permissive so no need to worry.

**Comment by ukH9YFxczKfxEnNECPyq** [comment]
does it mean, you accepted package?



Aug 1, 2020, 09:26 by notifications@github.com:

**Comment by ukH9YFxczKfxEnNECPyq** [comment]
ohh, sorry, previous message was not to you. about licence, got it. thank you for the answer



Aug 1, 2020, 09:26 by notifications@github.com:

**Comment by lockie** [comment]
@resttime Technically Allegro 5 license is [zlib](https://tldrlegal.com/license/zlib-libpng-license-(zlib)), you might want to tweak `:license` field in asd file accordingly. Or don't, I'm just passing by :)

**Comment by resttime** [comment]
Thanks! I'll make the changes, I actually had no idea lol
